### ISSUE TITLE
obstruction map colors

### ISSUE THREAD

**Issue by joeyh** [bmillham/starlink-graph#2]
The color scheme for the obstruction map makes it hard to notice small obstructions, where there may just be a few reddish pixels at the edge of a lot of blue. Especially ones where the red is less saturated.

The starlink-grpc-tools dish_obstruction_map.py color scheme of red/white/black has much higher contrast and works much better.

**Comment by bmillham** [comment]
Thank you for the feedback. I will add an option allowing you to customize the colors. I'll let you know when it's ready for testing.

**Comment by bmillham** [comment]
Just pushed a new version that allows you to customize the obstructions image color.
