### ISSUE TITLE
obstruction map auto-update

### ISSUE THREAD

**Issue by joeyh** [bmillham/starlink-graph#3]
I expected the obstruction window to automatically update, but reading the code I see that's not the case, and I have to click on the menu entry, which will update it (in place).

So, it seems like it would be easy to have it auto-update when the window is visible. This would be a great feature to be able to watch the tracks develop in real time, especially after boot.

**Comment by bmillham** [comment]
I actually was thinking about adding an option to keep a history of outages so a animation could be made over 12 hours. I'll look at also adding an option for live updates.

**Comment by bmillham** [comment]
Just pushed V 0.4 that has an option to update the map live (settable from ever 10-900 seconds in 10 second intervals) Maps are not saved, so no history (yet)
