### ISSUE TITLE
allow more frequent updates of obstructions

### ISSUE THREAD

**Issue by joeyh** [bmillham/starlink-graph#6]
Automatically updating the obstructions is currently limited to 10 seconds. Updating more frequently certianly is wasteful of CPU, but it can be very cool to see the tracks of birds update in real time, especially when the terminal has recently been powered on. So I suggest letting it be set to 1 second, which works well in my testing after modifying the code to allow it.
```

--- a/starlink-graph.glade
+++ b/starlink-graph.glade
@@ -17,7 +17,7 @@
     <property name="page-increment">10</property>
   </object>
   <object class="GtkAdjustment" id="obstructionadjustment">
-    <property name="lower">10</property>
+    <property name="lower">1</property>
     <property name="upper">900</property>
     <property name="value">10</property>
     <property name="step-increment">10</property>
```

(btw I had to guess what the units are in the config page)

**Comment by bmillham** [comment]
Done, changed the minimum to 1 second.

**Comment by bmillham** [comment]
Since no comments, I'm assuming my fix was what was requested.
